spring:
  # Redis配置
  redis:
    host: 10.173.211.10
    port: 6379
    password: hgrica1@
    database: 11
    expireTime: 86400
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 1000
